// Code generated by goctl. DO NOT EDIT.
package types

type AuthRequest struct {
	OriginUrl string `header:"origin_url,optional"`
	Token     string `header:"token,optional"`
}

type AuthResponse struct {
	UserID uint `json:"userID"`
	Role   int  `json:"role"`
}

type LoginRequest struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
}

type OpenLoginInfoResponse struct {
	Name string `json:"name"`
	Icon string `json:"icon"`
	Href string `json:"href"` // 跳转地址
}

type OpenLoginRequest struct {
	Code string `json:"code"`
	Flag string `json:"flag"`
}

type RegisterRequest struct {
	NickName string `json:"nickname"`
	Role     int32  `json:"role"`
	Pwd      string `json:"pwd"`
}

type Response struct {
	Data string `json:"data"`
}
