// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"fim_server/fim_user/user_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/users/friend_info",
				Handler: FriendInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/users/friends",
				Handler: FriendListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/users/user_info",
				Handler: UserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/users/user_info",
				Handler: UserInfoUpdateHandler(serverCtx),
			},
		},
	)
}
